# Generated by Django 2.2.2 on 2019-09-13 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('checkid', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('chname', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('checkout_user', models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pid', models.CharField(default='', max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('basicPrice', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(default=None, upload_to='images')),
                ('img3', models.ImageField(default=None, upload_to='images')),
                ('img4', models.ImageField(default=None, upload_to='images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('order_address', models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Checkout')),
                ('order_product', models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Product')),
                ('order_user', models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('order_address', models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Checkout')),
                ('order_product', models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Product')),
                ('order_user', models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('cart_product', models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Product')),
                ('cart_user', models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
